### ISSUE TITLE
adding updated constructor parameter in  hardhat-dao-fcc/contracts/governance_standard/TimeLock.sol contract

### ISSUE THREAD

**Issue by Tri-pathi** [PatrickAlphaC/hardhat-dao-fcc#13]
#Discription of admin(address) in TimelockController
*`TimelockController` : A new `admin` constructor parameter has been added and that is assigned the admin role instead of the deployer account, so we should add here too as in current repo older version is being used which is not compilable .([#3722](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3722))
In Current [TimeLock.sol](https://github.com/PatrickAlphaC/hardhat-dao-fcc/blob/main/contracts/governance_standard/TimeLock.sol)
we have only three  constructor parameters 
1. uint256 minDelay
2. address[] memory proposer
3. address[] memory executors

**Comment by Tarang-16** [comment]
Yeah! That's right!
If we do not provide admin parameter then it is showing the following error:
>Wrong argument count for modifier invocation: 3 arguments given but expected 4.

@PatrickAlphaC please consider updating this in the lesson 17.

**Comment by PatrickAlphaC** [comment]
Thanks all, I saw a few PRs on this. Would love to get a PR from someone who also updates the `TimeLock.sol` contract for all 4 parameters!

**Comment by Tri-pathi** [comment]
fine.... i will update this soon...

**Comment by Tri-pathi** [comment]
@PatrickAlphaC  just made a PR in dao-template by adding admin constructor and updating deploy script.Thanks

**Comment by PatrickAlphaC** [comment]
Thank you!!
